const mk = (overrides) => ({
  id: `t-${Math.random().toString(36).slice(2, 10)}`,
  customerName: "Walk-in",
  outfitType: "Blouse",
  title: "Sample task",
  description: "",
  departmentKey: "embroidery",
  status: "UNASSIGNED",
  assignedTo: "",
  previousTaskStatus: "—",
  estimatedHours: 2,
  priority: "medium",
  completed: false,
  completedAt: null,
  deadline: new Date().toISOString().slice(0, 10),
  orderId: "",
  notes: "",
  ...overrides,
});

/** Initial boutique tasks (local-first; not tied to /works API) */
export function buildInitialTasks() {
  return [
    mk({
      id: "seed-emb-1",
      customerName: "Mrs. Amika",
      outfitType: "Blouse",
      title: "Amika blouse — zardozi panel",
      description: "Front panel only; match swatch #Z12",
      departmentKey: "embroidery",
      status: "ASSIGNED",
      assignedTo: "rakesh",
      previousTaskStatus: "Marking — Assigned",
      estimatedHours: 4,
      priority: "high",
    }),
    mk({
      id: "seed-emb-2",
      customerName: "Rashika",
      outfitType: "Bridal Lehenga",
      title: "Rashika bridal blouse embroidery",
      departmentKey: "embroidery",
      status: "UNASSIGNED",
      assignedTo: "",
      previousTaskStatus: "Marking — Pending",
      estimatedHours: 3,
      priority: "high",
    }),
    mk({
      id: "seed-cut-1",
      customerName: "Mega",
      outfitType: "Kurta",
      title: "Mega umbrella kurta — cutting",
      departmentKey: "cutting",
      status: "ASSIGNED",
      assignedTo: "vinum",
      previousTaskStatus: "Embroidery — Complete",
      estimatedHours: 1.5,
      priority: "medium",
    }),
    mk({
      id: "seed-sew-1",
      customerName: "Divya",
      outfitType: "Gown",
      title: "Evening gown side zip",
      departmentKey: "sewing",
      status: "ASSIGNED",
      assignedTo: "taniya",
      previousTaskStatus: "Cutting — Complete",
      estimatedHours: 5,
      priority: "medium",
    }),
    mk({
      id: "seed-sew-2",
      customerName: "Kavya",
      outfitType: "Blouse",
      title: "Princess-cut blouse finishing seams",
      departmentKey: "sewing",
      status: "IN_PROGRESS",
      assignedTo: "kamali",
      previousTaskStatus: "Cutting — Complete",
      estimatedHours: 2.5,
      priority: "low",
    }),
    mk({
      id: "seed-fin-1",
      customerName: "Shaaz",
      outfitType: "Kurta",
      title: "Final press & thread trim",
      departmentKey: "finishes",
      status: "ASSIGNED",
      assignedTo: "priyanka",
      previousTaskStatus: "Sewing — Complete",
      estimatedHours: 1,
      priority: "medium",
    }),
    mk({
      id: "seed-mark-1",
      customerName: "Latha",
      outfitType: "Saree Fall & Pico",
      title: "Mark pleat drop + fall attachment",
      departmentKey: "marking",
      status: "UNASSIGNED",
      assignedTo: "",
      previousTaskStatus: "Order — Confirmed",
      estimatedHours: 0.75,
      priority: "low",
    }),
    mk({
      id: "seed-aari-1",
      customerName: "Ananya",
      outfitType: "Bridal Lehenga",
      title: "Aari border continuation",
      departmentKey: "aari",
      status: "ASSIGNED",
      assignedTo: "aishu",
      previousTaskStatus: "Embroidery — In progress",
      estimatedHours: 6,
      priority: "high",
    }),
    mk({
      id: "seed-done-1",
      customerName: "Jaya",
      outfitType: "Blouse",
      title: "Potli buttons — embroidery",
      departmentKey: "embroidery",
      status: "ASSIGNED",
      assignedTo: "santhosh",
      previousTaskStatus: "Marking — Complete",
      estimatedHours: 2,
      priority: "low",
      orderId: "#2026051210",
      completed: true,
      completedAt: Date.now() - 86400000 * 2,
    }),
    mk({
      id: "seed-done-2",
      customerName: "Meera",
      outfitType: "Kurta",
      title: "Kurta full construction",
      departmentKey: "sewing",
      status: "ASSIGNED",
      assignedTo: "anushka",
      previousTaskStatus: "Cutting — Complete",
      estimatedHours: 4,
      priority: "medium",
      orderId: "#2026051214",
      completed: true,
      completedAt: Date.now() - 86400000 * 1,
    }),
    mk({
      id: "seed-done-3",
      customerName: "anitha",
      outfitType: "Blouse",
      title: "cutting",
      departmentKey: "cutting",
      status: "ASSIGNED",
      assignedTo: "vinum",
      previousTaskStatus: "Marking — Assigned",
      estimatedHours: 2,
      priority: "medium",
      orderId: "#2026051215",
      completed: true,
      completedAt: Date.now() - 86400000,
    }),
  ];
}
